### ISSUE TITLE
Local Instance:  Error serializing `.title` returned from `getServerSideProps`

### ISSUE THREAD

**Issue by superczar** [debridmediamanager/debrid-media-manager#104]
Hi 
First up, excellent work on this project and can't thank you enough for this.
I was trying to setup a local instance on a ubuntu 20.04 server
The code compiles fine and works as expected up .
However when I try to search for something , the results load up fine.
However clicking on a search entry throws the following error.

Not sure what I am doing wrong - any pointers would be really appreciated
```
 q [Error]: Error serializing `.title` returned from `getServerSideProps` in "/show/[imdbid]/[seasonNum]".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
    at r (/home/abhinav/debrid-media-manager/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:30:446)
    at /home/abhinav/debrid-media-manager/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:30:683
    at Array.every (<anonymous>)
    at r (/home/abhinav/debrid-media-manager/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:30:580)
    at H (/home/abhinav/debrid-media-manager/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:30:1117)
    at eZ (/home/abhinav/debrid-media-manager/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:47:1510)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async doRender (/home/abhinav/debrid-media-manager/node_modules/next/dist/server/base-server.js:1266:26)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (/home/abhinav/debrid-media-manager/node_modules/next/dist/server/base-server.js:1446:28)
    at async DevServer.renderToResponseWithComponentsImpl (/home/abhinav/debrid-media-manager/node_modules/next/dist/server/base-server.js:1361:28)
    at async DevServer.renderPageComponent (/home/abhinav/debrid-media-manager/node_modules/next/dist/server/base-server.js:1600:24)
    at async DevServer.renderToResponseImpl (/home/abhinav/debrid-media-manager/node_modules/next/dist/server/base-server.js:1638:32)
    at async DevServer.pipeImpl (/home/abhinav/debrid-media-manager/node_modules/next/dist/server/base-server.js:826:25)
    at async DevServer.handleCatchallRenderRequest (/home/abhinav/debrid-media-manager/node_modules/next/dist/server/next-server.js:623:13)
    at async DevServer.handleRequestImpl (/home/abhinav/debrid-media-manager/node_modules/next/dist/server/base-server.js:728:17) {
  page: '/show/tt7772588/1'

```

**Comment by yowmamasita** [comment]
Closing this as stale. Self-hosting has moved on a long way since you hit this, and none of the pieces in your report are still how it works: PlanetScale is gone, the schema is different, and the proxy and env setup you were following have been replaced.

If you want to self-host today, start from the current README rather than from this thread, and open a fresh issue if it fails, with what you ran and what it said.
