### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information)

### ISSUE THREAD

**Issue by hudson-thomas** [debridmediamanager/debrid-media-manager#95]
Hi!

Just setup a self-hosted instance using Docker and I absolutely love it! However, I am having an issue with the search function. It appears to be the same issue referenced in a [Reddit post ](https://www.reddit.com/r/debridmediamanager/comments/18jpm2w/comment/kdls21x/?utm_source=share&utm_medium=web2x&context=3)from a few days ago.

No matter the search term, the search throws this error in the browser: 
`Application error: a client-side exception has occurred (see the browser console for more information).`

Docker logs: 
```
encountered a search issue PrismaClientKnownRequestError: 

Invalid prisma.search.findUnique() invocation:

The table (not available) does not exist in the current database.

    at si.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:125:6817)

    at si.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:125:6151)

    at si.request (/app/node_modules/@prisma/client/runtime/library.js:125:5859)

    at async l (/app/node_modules/@prisma/client/runtime/library.js:130:10025)

    at async PlanetScaleCache.getSearchResults (/app/.next/server/chunks/9432.js:1:3819)

    at async handler (/app/.next/server/pages/api/search/title.js:1:1226) {

  code: 'P2021',

  clientVersion: '5.7.0',

  meta: { modelName: 'Search', table: '(not available)' }

}
```

Firefox inspect:

```
Source Map URL: purify.min.js.map
TypeError: d is undefined
    NextJS 30
framework-0c7baedefba6b077.js:9:69878
TypeError: d is undefined
    NextJS 30
main-c379b48138cf9870.js:1:10882
A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred main-c379b48138cf9870.js:1:10899

```

If you need more info to debug, just let me know!

**Comment by yowmamasita** [comment]
Hi, did you setup the tables?

**Comment by hudson-thomas** [comment]
Yes, but I'll close this issue anyway. The version you host is perfectly reliable so I just use that. Thanks!
